-- ============================================================================
-- AgriGrade AI – Schema Enhancement Migration (V2)
-- Refresh Token Family Rotation & Batch Media Metadata Capabilities
-- ============================================================================
--
-- V2 schema changes were already applied manually to the TiDB database
-- because TiDB DDL is non-transactional and the original migration
-- partially completed before failing.
--
-- Existing changes:
-- refresh_tokens:
--   family_id
--   revoked_at
--   replaced_by_token_id
--   fk_rt_replaced_by
--
-- batch_images:
--   media_type
--   mime_type
--   file_size_bytes
--
-- This migration is intentionally empty because the schema changes
-- already exist in the database.
-- ============================================================================

SELECT 1;